### ISSUE TITLE
CKeditor4 Error [ CKEDITOR] Error code: invalid-lts-license-key.

### ISSUE THREAD

**Issue by kaanakyuz** [open-admin-org/ckeditor#2]
CKeditor4 Getting Error on console * [ CKEDITOR] Error code: invalid-lts-license-key.

how can we fix that ? 

+ Found composer.lock  "version": "4.23.0", doesnt work correctly ,
+ Also previous project on  composer.lock "version": "4.22.1", work correctly.

Tryed new install and see   - Locking ckeditor/ckeditor (4.23.0) ... how can i change to 4.22.1 ?

Solution
+  i copied on previous project public/vendor/open-admin-ext folder to new one , its working now

**But on all new project CKeditor wont work.**

**Comment by priyanshiisingh** [comment]
@kaanakyuz  any luck finding a solution for new projects?

**Comment by vneet2057** [comment]
Is there any substitute for editor if yes please update the docs thanks

**Comment by AliHassan002** [comment]
i'm still facing this issue . is there any solution to this. or is there any way to implement any open source editor in the open admin panel which works well.

**Comment by priyanshiisingh** [comment]
@vneet2057 @AliHassan002 I've integrated Quill editor with open-admin

**Comment by priyanshiisingh** [comment]
@vneet2057 @AliHassan002 I've integrated Quill editor with open-admin, you can use quill's cdn libraries to implement it directly into the open admin textarea component. You can find them in the vendor/open-admin/ folder.

**Comment by AliHassan002** [comment]
@priyanshiisingh  thanks for the help. is there any guide on how to integrate it with admin panel, it will be of great help.

**Comment by priyanshiisingh** [comment]
> @priyanshiisingh thanks for the help. is there any guide on how to integrate it with admin panel, it will be of great help.

There isn't any guide available I've configured it by my own for now. The catch with it is I'm unable to create 2 textareas in a single form. So, If you want to editors in a single form you'll have to create new named components for the same.

I can share my code if you want.

**Comment by priyanshiisingh** [comment]
@AliHassan002 There isn't any guide available I've configured it by my own for now. The catch with it is I'm unable to create 2 textareas in a single form. So, If you want to editors in a single form you'll have to create new named components for each of them.

I can share my code if you want.

**Comment by priyanshiisingh** [comment]
@AliHassan002 There isn't any guide available I've configured it by my own for now. The catch with it is I'm unable to create 2 editors in a single form. So, If you want 2 editors in a single form you'll have to create new named components for each of them in the root vendor/open-admin-org/ folder.

I can share my code if you want.

**Comment by aleksandro-del-piero** [comment]
The official website says that from version 4.23 you need to buy a license. Update the package at public/vencor/open-admin-ext/ckeditor to version 4.22.0/4.22.1 and everything will work for you.

**Comment by open-admin-org** [comment]
@all sorry for the late reply.
@aleksandro-del-piero thanks for the research. I locked the version at 4.21. 
4.22 was also giving some weird request error.
