### ISSUE TITLE
Css can't load

### ISSUE THREAD

**Issue by muhammadrafihq** [open-admin-org/ckeditor#4]
<img width="872" alt="Screen Shot 2023-11-29 at 14 13 24" src="https://github.com/open-admin-org/ckeditor/assets/98201124/70a9ad80-2ec2-4dfb-91ce-fd39509c5f12">
can someone help me? why css ckeditor can't load?

**Comment by open-admin-org** [comment]
Is your file accessible? (right click: open in new tab)
